### ISSUE TITLE
Only works with Phoenix 0.9-dev?

### ISSUE THREAD

**Issue by os6sense** [etufe/phoenix_generator#2]
Hi, great project! I had some problems due to the changes in Plug and csrf which I assume means that this only works with the latest (github) version of Phoenix - worth noting in the readme?

**Comment by itsgreggreg** [comment]
Hey, yeah definitely, thanks! Did you end up getting it to work for you?

**Comment by os6sense** [comment]
Once I worked out what the CSRF problem was and upgraded phoenix it all worked as documented although I've only used it for one page yet!
