### ISSUE TITLE
app file disappears when running mix task

### ISSUE THREAD

**Issue by knewter** [etufe/phoenix_generator#4]
So I can't see how this would be an issue with this project specifically, but thought I'd give some feedback at least.  Trying to follow the readme from this project doesn't work, and I end up with this: https://gist.github.com/knewter/3a0b613cc792b7f4931c

Essentially, when I try to run the generator for a scaffold, it will delete my .app file, then freak out because it doesn't exist.  I haven't dug in any yet, so I don't know where the issue is.  It's reproducible if you do the following:

```
hub clone knewter/phoenix_blog
cd phoenix_blog
git checkout start
mix deps.get
mix compile
mix phoenix.gen.jumpstart
# Modify the config/config.exs file so you can make a db
mix ecto.create
```

At this point, if you `mix compile`, you'll get an .app file.  If you then run:

```
mix phoenix.gen.scaffold post title:string body:string
```

It will error out as described in the gist.  The .app file is now missing.  No clue :-\  Computers...

**Comment by itsgreggreg** [comment]
Cool, thanks for the note. Looking into it!

**Comment by itsgreggreg** [comment]
Should be fixed now! Remember to update with `mix deps.update only: phoenix_generator` .

It use to not recompile the router upon editing it for some reason, so I would manually clean the project. Looks like now the router gets properly recompiled and cleaning the project manually breaks it. :)

Thanks again for the bug report!

**Comment by knewter** [comment]
Sweet.  It was such an odd error, I wasn't anticipating a quick fix :)  Thanks.
