### ISSUE TITLE
Compilation error on file web/channels/instachat_channel.ex

### ISSUE THREAD

**Issue by hopewise** [etufe/phoenix_generator#6]
I tried `mix phoenix.gen.instachat`, but I got:

```
== Compilation error on file web/channels/instachat_channel.ex ==
** (CompileError) web/channels/instachat_channel.ex:8: undefined function reply/3
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

can you help please? thanks

**Comment by itsgreggreg** [comment]
These generators are deprecated and completely unsupported at this time. The code is just up for historical and learning purposes. I released a video showing how to make a simple chat in phoenix here: https://www.youtube.com/watch?v=e5jlIejl9Fs good luck!
